version: '3'

networks:
  nginx-php-mysql-node:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
      - mysql-service
    networks:
      - nginx-php-mysql-node

  # php
  php-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php-mysql-node

  # mysql
  mysql-service:
    image: mysql:8
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: personal-website
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
      - nginx-php-mysql-node

  # node
  node-service:
    image: node:latest
    container_name: node-container
    volumes:
      - ./app:/var/www/project
    working_dir: /var/www/project
    networks:
      - nginx-php-mysql-node